<?php
// Database Installer for Apollo Cleaning Services

$message = '';
$status = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_name = $_POST['db_name'] ?? 'apollo_db';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';

    // Test connection
    try {
        $conn = new mysqli($db_host, $db_user, $db_pass);
        if ($conn->connect_error) {
            throw new Exception("Connection failed: " . $conn->connect_error);
        }

        // Create database if not exists
        $db_name_escaped = $conn->real_escape_string($db_name);
        if (!$conn->query("CREATE DATABASE IF NOT EXISTS `$db_name_escaped` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")) {
            throw new Exception("Error creating database: " . $conn->error);
        }

        $conn->select_db($db_name);

        // Read and execute database.sql
        if (file_exists('database.sql')) {
            $sql = file_get_contents('database.sql');
            
            // Execute multi query
            if ($conn->multi_query($sql)) {
                // Clear results
                do {
                    if ($result = $conn->store_result()) {
                        $result->free();
                    }
                } while ($conn->next_result());
            } else {
                throw new Exception("Error running schema: " . $conn->error);
            }
        } else {
            throw new Exception("Schema file (database.sql) not found.");
        }

        // Create api directory if it doesn't exist
        if (!is_dir('api')) {
            mkdir('api', 0755, true);
        }

        // Write api/config.php
        $config_content = "<?php\n"
            . "// Database Configuration - Auto-generated by install.php\n\n"
            . "define('DB_HOST', '" . addslashes($db_host) . "');\n"
            . "define('DB_NAME', '" . addslashes($db_name) . "');\n"
            . "define('DB_USER', '" . addslashes($db_user) . "');\n"
            . "define('DB_PASS', '" . addslashes($db_pass) . "');\n\n"
            . "// Toggle settings\n"
            . "define('TEST_MODE', true);\n"
            . "?>";

        if (file_put_contents('api/config.php', $config_content) === false) {
            throw new Exception("Failed to write api/config.php. Check folder permissions.");
        }

        $status = 'success';
        $message = "Database configured and initialized successfully! You can now log into the <a href='admin/login.php' style='color:#ffffff;text-decoration:underline;'>Admin Panel</a> (username: <strong>admin</strong>, password: <strong>password123</strong>).";

    } catch (Exception $e) {
        $status = 'error';
        $message = "Installation Error: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Database Setup — Apollo Cleaning Platform</title>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: 'Manrope', Arial, sans-serif;
      margin: 0;
      background: #f7f7f7;
      color: #1a1a1a;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 20px;
    }
    .install-box {
      background: #ffffff;
      border-radius: 16px;
      border: 1px solid #e8e8e8;
      box-shadow: 0 4px 20px rgba(26,26,26,0.06);
      width: 100%;
      max-width: 480px;
      padding: 40px;
    }
    .logo-container {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 24px;
    }
    .logo-badge {
      width: 42px;
      height: 42px;
      border-radius: 8px;
      background: #1B3E6B;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #ffffff;
      font-weight: 700;
      font-size: 20px;
    }
    h1 {
      font-size: 24px;
      font-weight: 600;
      letter-spacing: -0.5px;
      margin: 0;
      color: #1a1a1a;
    }
    .desc {
      font-size: 14.5px;
      line-height: 1.4;
      color: #636363;
      margin: 0 0 30px;
    }
    .form-group {
      margin-bottom: 20px;
    }
    label {
      display: block;
      font-size: 13.5px;
      font-weight: 600;
      color: #3d3d3d;
      margin-bottom: 8px;
    }
    input {
      width: 100%;
      height: 46px;
      border-radius: 6px;
      border: 1px solid #c2c2c2;
      padding: 0 16px;
      font-family: inherit;
      font-size: 14.5px;
      outline: none;
      transition: border-color 0.2s;
    }
    input:focus {
      border-color: #1B3E6B;
    }
    button {
      width: 100%;
      height: 48px;
      border-radius: 6px;
      border: none;
      background: #1B3E6B;
      color: #ffffff;
      font-weight: 600;
      font-size: 15px;
      cursor: pointer;
      margin-top: 10px;
      transition: background 0.2s;
    }
    button:hover {
      background: #150F38;
    }
    .alert {
      padding: 16px 20px;
      border-radius: 8px;
      font-size: 14px;
      line-height: 1.45;
      margin-bottom: 24px;
    }
    .alert-success {
      background: #22c55e;
      color: #ffffff;
    }
    .alert-error {
      background: #ef4444;
      color: #ffffff;
    }
  </style>
</head>
<body>
  <div class="install-box">
    <div class="logo-container">
      <div class="logo-badge">A</div>
      <h1>Database Setup</h1>
    </div>
    <p class="desc">Configure your MySQL database connection to modernize and activate the Apollo Support Services platform.</p>

    <?php if ($message): ?>
      <div class="alert alert-<?php echo $status; ?>">
        <?php echo $message; ?>
      </div>
    <?php endif; ?>

    <?php if ($status !== 'success'): ?>
      <form method="POST" action="">
        <div class="form-group">
          <label for="db_host">Database Host</label>
          <input type="text" id="db_host" name="db_host" value="localhost" required>
        </div>
        <div class="form-group">
          <label for="db_name">Database Name</label>
          <input type="text" id="db_name" name="db_name" value="apollo_db" required>
        </div>
        <div class="form-group">
          <label for="db_user">Database User</label>
          <input type="text" id="db_user" name="db_user" value="root" required>
        </div>
        <div class="form-group">
          <label for="db_pass">Database Password</label>
          <input type="password" id="db_pass" name="db_pass" value="">
        </div>
        <button type="submit">Configure &amp; Install</button>
      </form>
    <?php endif; ?>
  </div>
</body>
</html>
